# Generated by Django 4.1.7 on 2023-03-24 07:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects_primavera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='endate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='observation',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
