# Generated by Django 4.1.7 on 2023-03-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_primavera', '0002_project_activity_project_endate_project_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='endate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='observation',
        ),
    ]
