# Generated by Django 4.1.7 on 2023-03-24 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_primavera', '0003_remove_project_activity_remove_project_endate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('observation', models.TextField()),
                ('endate', models.DateField(verbose_name=datetime.date.today)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_primavera.project')),
            ],
        ),
    ]
