# Generated by Django 4.1.7 on 2023-03-24 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects_primavera', '0004_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='proyect',
        ),
        migrations.AddField(
            model_name='activities',
            name='activity',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_primavera.project'),
        ),
    ]
