# Generated by Django 4.1.7 on 2023-03-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_primavera', '0005_remove_activities_proyect_activities_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='title',
            new_name='nombreProyect',
        ),
    ]
