# Generated by Django 4.1.7 on 2023-03-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_primavera', '0006_rename_title_activities_nombreproyect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='nombreProyect',
            new_name='title',
        ),
    ]
